config/routes.rb
Rails.application.routes.draw do
  resources :compania

  resources :localizacions

  resources :locals

  resources :filtros

  resources :diccionarios

  resources :reclamos

  resources :tweets

  resources :usuarios

end

app/models/compania.rb
class Compania < ActiveRecord::Base
end

app/models/diccionario.rb
class Diccionario < ActiveRecord::Base
end

app/models/filtro.rb
class Filtro < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base
end

app/models/localizacion.rb
class Localizacion < ActiveRecord::Base
end

app/models/reclamo.rb
class Reclamo < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/tweet_filtro.rb
class TweetFiltro < ActiveRecord::Base
end

app/models/twwet_diccionario.rb
class TwwetDiccionario < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/usuario_tweet.rb
class UsuarioTweet < ActiveRecord::Base
end

app/controllers/compania_controller.rb
class CompaniaController < ApplicationController
  before_action :set_companium, only: [:show, :edit, :update, :destroy]

  def index
    @compania = Companium.all
    respond_with(@compania)
  end

  def show
    respond_with(@companium)
  end

  def new
    @companium = Companium.new
    respond_with(@companium)
  end

  def edit
  end

  def create
    @companium = Companium.new(companium_params)
    @companium.save
    respond_with(@companium)
  end

  def update
    @companium.update(companium_params)
    respond_with(@companium)
  end

  def destroy
    @companium.destroy
    respond_with(@companium)
  end

  private
    def set_companium
      @companium = Companium.find(params[:id])
    end

    def companium_params
      params.require(:companium).permit(:nombre, :cuenta, :twit)
    end
end

app/controllers/filtros_controller.rb
class FiltrosController < ApplicationController
  before_action :set_filtro, only: [:show, :edit, :update, :destroy]

  # GET /filtros
  # GET /filtros.json
  def index
    @filtros = Filtro.all
  end

  # GET /filtros/1
  # GET /filtros/1.json
  def show
  end

  # GET /filtros/new
  def new
    @filtro = Filtro.new
  end

  # GET /filtros/1/edit
  def edit
  end

  # POST /filtros
  # POST /filtros.json
  def create
    @filtro = Filtro.new(filtro_params)

    respond_to do |format|
      if @filtro.save
        format.html { redirect_to @filtro, notice: 'Filtro was successfully created.' }
        format.json { render :show, status: :created, location: @filtro }
      else
        format.html { render :new }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filtros/1
  # PATCH/PUT /filtros/1.json
  def update
    respond_to do |format|
      if @filtro.update(filtro_params)
        format.html { redirect_to @filtro, notice: 'Filtro was successfully updated.' }
        format.json { render :show, status: :ok, location: @filtro }
      else
        format.html { render :edit }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filtros/1
  # DELETE /filtros/1.json
  def destroy
    @filtro.destroy
    respond_to do |format|
      format.html { redirect_to filtros_url, notice: 'Filtro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filtro
      @filtro = Filtro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filtro_params
      params.require(:filtro).permit(:tipo, :termino)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:contenido, :fecha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compania_helper.rb
module CompaniaHelper
end

app/helpers/diccionarios_helper.rb
module DiccionariosHelper
end

app/helpers/filtros_helper.rb
module FiltrosHelper
end

app/helpers/localizacions_helper.rb
module LocalizacionsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/reclamos_helper.rb
module ReclamosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/compania/_form.html.erb
<%= form_for(@companium) do |f| %>
  <% if @companium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@companium.errors.count, "error") %> prohibited this companium from being saved:</h2>

      <ul>
      <% @companium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :cuenta %><br>
    <%= f.number_field :cuenta %>
  </div>
  <div class="field">
    <%= f.label :twit %><br>
    <%= f.text_field :twit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compania/edit.html.erb
<h1>Editing companium</h1>

<%= render 'form' %>

<%= link_to 'Show', @companium %> |
<%= link_to 'Back', compania_path %>

app/views/compania/index.html.erb
<h1>Listing compania</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cuenta</th>
      <th>Twit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compania.each do |companium| %>
      <tr>
        <td><%= companium.nombre %></td>
        <td><%= companium.cuenta %></td>
        <td><%= companium.twit %></td>
        <td><%= link_to 'Show', companium %></td>
        <td><%= link_to 'Edit', edit_companium_path(companium) %></td>
        <td><%= link_to 'Destroy', companium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Companium', new_companium_path %>

app/views/compania/new.html.erb
<h1>New companium</h1>

<%= render 'form' %>

<%= link_to 'Back', compania_path %>

app/views/compania/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @companium.nombre %>
</p>

<p>
  <strong>Cuenta:</strong>
  <%= @companium.cuenta %>
</p>

<p>
  <strong>Twit:</strong>
  <%= @companium.twit %>
</p>

<%= link_to 'Edit', edit_companium_path(@companium) %> |
<%= link_to 'Back', compania_path %>

app/views/filtros/_form.html.erb
<%= form_for @filtro, :html => { :class => "form-horizontal filtro" } do |f| %>

    <% if @filtro.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@filtro.errors.count, "error") %> prohibited this filtro from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @filtro.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :tipo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tipo, :class => 'form-control' %>
    </div>
    <%= error_span(@filtro[:tipo]) %>
  </div>
  <div class="control-group">
    <%= f.label :termino, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :termino, :class => 'form-control' %>
    </div>
    <%= error_span(@filtro[:termino]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            filtros_path, :class => 'btn btn-default' %>

<% end %>

app/views/filtros/edit.html.erb
<%- model_class = Filtro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/filtros/index.html.erb
<%- model_class = Filtro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:tipo) %></th>
      <th><%= model_class.human_attribute_name(:termino) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @filtros.each do |filtro| %>
      <tr>
        <td><%= link_to filtro.id, filtro_path(filtro) %></td>
        <td><%= filtro.tipo %></td>
        <td><%= filtro.termino %></td>
        <td><%=l filtro.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_filtro_path(filtro), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      filtro_path(filtro),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_filtro_path,
            :class => 'btn btn-primary' %>

app/views/filtros/new.html.erb
<%- model_class = Filtro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/filtros/show.html.erb
<%- model_class = Filtro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tipo) %>:</strong></dt>
  <dd><%= @filtro.tipo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:termino) %>:</strong></dt>
  <dd><%= @filtro.termino %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              filtros_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_filtro_path(@filtro), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              filtro_path(@filtro),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/tweets/_form.html.erb
<%= form_for @tweet, :html => { :class => "form-horizontal tweet" } do |f| %>

    <% if @tweet.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :contenido, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contenido, :class => 'form-control' %>
    </div>
    <%= error_span(@tweet[:contenido]) %>
  </div>
  <div class="control-group">
    <%= f.label :fecha, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fecha, :class => 'form-control' %>
    </div>
    <%= error_span(@tweet[:fecha]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            tweets_path, :class => 'btn btn-default' %>

<% end %>

app/views/tweets/edit.html.erb
<%- model_class = Tweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tweets/index.html.erb
<%- model_class = Tweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:contenido) %></th>
      <th><%= model_class.human_attribute_name(:fecha) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= link_to tweet.id, tweet_path(tweet) %></td>
        <td><%= tweet.contenido %></td>
        <td><%= tweet.fecha %></td>
        <td><%=l tweet.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tweet_path(tweet), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tweet_path(tweet),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tweet_path,
            :class => 'btn btn-primary' %>

app/views/tweets/new.html.erb
<%- model_class = Tweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tweets/show.html.erb
<%- model_class = Tweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:contenido) %>:</strong></dt>
  <dd><%= @tweet.contenido %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha) %>:</strong></dt>
  <dd><%= @tweet.fecha %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tweets_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tweet_path(@tweet), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tweet_path(@tweet),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>