config/routes.rb
Rails.application.routes.draw do
  resources :compania

  resources :localizacions

  resources :locals

  resources :filtros

  resources :diccionarios

  resources :reclamos

  resources :tweets

  resources :usuarios

end

app/models/compania.rb
class Compania < ActiveRecord::Base
end

app/models/diccionario.rb
class Diccionario < ActiveRecord::Base
end

app/models/filtro.rb
class Filtro < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base
end

app/models/localizacion.rb
class Localizacion < ActiveRecord::Base
end

app/models/reclamo.rb
class Reclamo < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/tweet_filtro.rb
class TweetFiltro < ActiveRecord::Base
end

app/models/twwet_diccionario.rb
class TwwetDiccionario < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/usuario_tweet.rb
class UsuarioTweet < ActiveRecord::Base
end

app/controllers/filtros_controller.rb
class FiltrosController < ApplicationController
  before_action :set_filtro, only: [:show, :edit, :update, :destroy]

  # GET /filtros
  # GET /filtros.json
  def index
    @filtros = Filtro.all
  end

  # GET /filtros/1
  # GET /filtros/1.json
  def show
  end

  # GET /filtros/new
  def new
    @filtro = Filtro.new
  end

  # GET /filtros/1/edit
  def edit
  end

  # POST /filtros
  # POST /filtros.json
  def create
    @filtro = Filtro.new(filtro_params)

    respond_to do |format|
      if @filtro.save
        format.html { redirect_to @filtro, notice: 'Filtro was successfully created.' }
        format.json { render :show, status: :created, location: @filtro }
      else
        format.html { render :new }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filtros/1
  # PATCH/PUT /filtros/1.json
  def update
    respond_to do |format|
      if @filtro.update(filtro_params)
        format.html { redirect_to @filtro, notice: 'Filtro was successfully updated.' }
        format.json { render :show, status: :ok, location: @filtro }
      else
        format.html { render :edit }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filtros/1
  # DELETE /filtros/1.json
  def destroy
    @filtro.destroy
    respond_to do |format|
      format.html { redirect_to filtros_url, notice: 'Filtro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filtro
      @filtro = Filtro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filtro_params
      params.require(:filtro).permit(:tipo, :termino)
    end
end

app/controllers/localizacions_controller.rb
class LocalizacionsController < ApplicationController
  before_action :set_localizacion, only: [:show, :edit, :update, :destroy]

  # GET /localizacions
  # GET /localizacions.json
  def index
    @localizacions = Localizacion.all
  end

  # GET /localizacions/1
  # GET /localizacions/1.json
  def show
  end

  # GET /localizacions/new
  def new
    @localizacion = Localizacion.new
  end

  # GET /localizacions/1/edit
  def edit
  end

  # POST /localizacions
  # POST /localizacions.json
  def create
    @localizacion = Localizacion.new(localizacion_params)

    respond_to do |format|
      if @localizacion.save
        format.html { redirect_to @localizacion, notice: 'Localizacion was successfully created.' }
        format.json { render :show, status: :created, location: @localizacion }
      else
        format.html { render :new }
        format.json { render json: @localizacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localizacions/1
  # PATCH/PUT /localizacions/1.json
  def update
    respond_to do |format|
      if @localizacion.update(localizacion_params)
        format.html { redirect_to @localizacion, notice: 'Localizacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @localizacion }
      else
        format.html { render :edit }
        format.json { render json: @localizacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localizacions/1
  # DELETE /localizacions/1.json
  def destroy
    @localizacion.destroy
    respond_to do |format|
      format.html { redirect_to localizacions_url, notice: 'Localizacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localizacion
      @localizacion = Localizacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def localizacion_params
      params.require(:localizacion).permit(:region)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:contenido, :fecha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compania_helper.rb
module CompaniaHelper
end

app/helpers/diccionarios_helper.rb
module DiccionariosHelper
end

app/helpers/filtros_helper.rb
module FiltrosHelper
end

app/helpers/localizacions_helper.rb
module LocalizacionsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/reclamos_helper.rb
module ReclamosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/localizacions/_form.html.erb
<%= form_for @localizacion, :html => { :class => "form-horizontal localizacion" } do |f| %>

    <% if @localizacion.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@localizacion.errors.count, "error") %> prohibited this localizacion from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @localizacion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :region, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :region, :class => 'form-control' %>
    </div>
    <%= error_span(@localizacion[:region]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            localizacions_path, :class => 'btn btn-default' %>

<% end %>

app/views/localizacions/edit.html.erb
<%- model_class = Localizacion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/localizacions/index.html.erb
<%- model_class = Localizacion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:region) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @localizacions.each do |localizacion| %>
      <tr>
        <td><%= link_to localizacion.id, localizacion_path(localizacion) %></td>
        <td><%= localizacion.region %></td>
        <td><%=l localizacion.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_localizacion_path(localizacion), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      localizacion_path(localizacion),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_localizacion_path,
            :class => 'btn btn-primary' %>

app/views/localizacions/new.html.erb
<%- model_class = Localizacion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/localizacions/show.html.erb
<%- model_class = Localizacion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:region) %>:</strong></dt>
  <dd><%= @localizacion.region %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              localizacions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_localizacion_path(@localizacion), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              localizacion_path(@localizacion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>