config/routes.rb
Rails.application.routes.draw do
  resources :compania

  resources :localizacions

  resources :locals

  resources :filtros

  resources :diccionarios

  resources :reclamos

  resources :tweets

  resources :usuarios

end

app/models/compania.rb
class Compania < ActiveRecord::Base
end

app/models/diccionario.rb
class Diccionario < ActiveRecord::Base
end

app/models/filtro.rb
class Filtro < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base
end

app/models/localizacion.rb
class Localizacion < ActiveRecord::Base
end

app/models/reclamo.rb
class Reclamo < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/tweet_filtro.rb
class TweetFiltro < ActiveRecord::Base
end

app/models/twwet_diccionario.rb
class TwwetDiccionario < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/usuario_tweet.rb
class UsuarioTweet < ActiveRecord::Base
end

app/controllers/diccionarios_controller.rb
class DiccionariosController < ApplicationController
  before_action :set_diccionario, only: [:show, :edit, :update, :destroy]

  # GET /diccionarios
  # GET /diccionarios.json
  def index
    @diccionarios = Diccionario.all
  end

  # GET /diccionarios/1
  # GET /diccionarios/1.json
  def show
  end

  # GET /diccionarios/new
  def new
    @diccionario = Diccionario.new
  end

  # GET /diccionarios/1/edit
  def edit
  end

  # POST /diccionarios
  # POST /diccionarios.json
  def create
    @diccionario = Diccionario.new(diccionario_params)

    respond_to do |format|
      if @diccionario.save
        format.html { redirect_to @diccionario, notice: 'Diccionario was successfully created.' }
        format.json { render :show, status: :created, location: @diccionario }
      else
        format.html { render :new }
        format.json { render json: @diccionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diccionarios/1
  # PATCH/PUT /diccionarios/1.json
  def update
    respond_to do |format|
      if @diccionario.update(diccionario_params)
        format.html { redirect_to @diccionario, notice: 'Diccionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @diccionario }
      else
        format.html { render :edit }
        format.json { render json: @diccionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diccionarios/1
  # DELETE /diccionarios/1.json
  def destroy
    @diccionario.destroy
    respond_to do |format|
      format.html { redirect_to diccionarios_url, notice: 'Diccionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diccionario
      @diccionario = Diccionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diccionario_params
      params.require(:diccionario).permit(:terminos)
    end
end

app/controllers/filtros_controller.rb
class FiltrosController < ApplicationController
  before_action :set_filtro, only: [:show, :edit, :update, :destroy]

  # GET /filtros
  # GET /filtros.json
  def index
    @filtros = Filtro.all
  end

  # GET /filtros/1
  # GET /filtros/1.json
  def show
  end

  # GET /filtros/new
  def new
    @filtro = Filtro.new
  end

  # GET /filtros/1/edit
  def edit
  end

  # POST /filtros
  # POST /filtros.json
  def create
    @filtro = Filtro.new(filtro_params)

    respond_to do |format|
      if @filtro.save
        format.html { redirect_to @filtro, notice: 'Filtro was successfully created.' }
        format.json { render :show, status: :created, location: @filtro }
      else
        format.html { render :new }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filtros/1
  # PATCH/PUT /filtros/1.json
  def update
    respond_to do |format|
      if @filtro.update(filtro_params)
        format.html { redirect_to @filtro, notice: 'Filtro was successfully updated.' }
        format.json { render :show, status: :ok, location: @filtro }
      else
        format.html { render :edit }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filtros/1
  # DELETE /filtros/1.json
  def destroy
    @filtro.destroy
    respond_to do |format|
      format.html { redirect_to filtros_url, notice: 'Filtro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filtro
      @filtro = Filtro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filtro_params
      params.require(:filtro).permit(:tipo, :termino)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:contenido, :fecha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compania_helper.rb
module CompaniaHelper
end

app/helpers/diccionarios_helper.rb
module DiccionariosHelper
end

app/helpers/filtros_helper.rb
module FiltrosHelper
end

app/helpers/localizacions_helper.rb
module LocalizacionsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/reclamos_helper.rb
module ReclamosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/diccionarios/_form.html.erb
<%= form_for @diccionario, :html => { :class => "form-horizontal diccionario" } do |f| %>

    <% if @diccionario.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@diccionario.errors.count, "error") %> prohibited this diccionario from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @diccionario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :terminos, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :terminos, :class => 'form-control' %>
    </div>
    <%= error_span(@diccionario[:terminos]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            diccionarios_path, :class => 'btn btn-default' %>

<% end %>

app/views/diccionarios/edit.html.erb
<%- model_class = Diccionario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diccionarios/index.html.erb
<%- model_class = Diccionario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:terminos) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @diccionarios.each do |diccionario| %>
      <tr>
        <td><%= link_to diccionario.id, diccionario_path(diccionario) %></td>
        <td><%= diccionario.terminos %></td>
        <td><%=l diccionario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_diccionario_path(diccionario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      diccionario_path(diccionario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_diccionario_path,
            :class => 'btn btn-primary' %>

app/views/diccionarios/new.html.erb
<%- model_class = Diccionario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diccionarios/show.html.erb
<%- model_class = Diccionario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:terminos) %>:</strong></dt>
  <dd><%= @diccionario.terminos %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              diccionarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_diccionario_path(@diccionario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              diccionario_path(@diccionario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>