config/routes.rb
Rails.application.routes.draw do
  resources :compania

  resources :localizacions

  resources :locals

  resources :filtros

  resources :diccionarios

  resources :reclamos

  resources :tweets

  resources :usuarios

end

app/models/compania.rb
class Compania < ActiveRecord::Base
end

app/models/diccionario.rb
class Diccionario < ActiveRecord::Base
end

app/models/filtro.rb
class Filtro < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base
end

app/models/localizacion.rb
class Localizacion < ActiveRecord::Base
end

app/models/reclamo.rb
class Reclamo < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/tweet_filtro.rb
class TweetFiltro < ActiveRecord::Base
end

app/models/twwet_diccionario.rb
class TwwetDiccionario < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/usuario_tweet.rb
class UsuarioTweet < ActiveRecord::Base
end

app/controllers/filtros_controller.rb
class FiltrosController < ApplicationController
  before_action :set_filtro, only: [:show, :edit, :update, :destroy]

  # GET /filtros
  # GET /filtros.json
  def index
    @filtros = Filtro.all
  end

  # GET /filtros/1
  # GET /filtros/1.json
  def show
  end

  # GET /filtros/new
  def new
    @filtro = Filtro.new
  end

  # GET /filtros/1/edit
  def edit
  end

  # POST /filtros
  # POST /filtros.json
  def create
    @filtro = Filtro.new(filtro_params)

    respond_to do |format|
      if @filtro.save
        format.html { redirect_to @filtro, notice: 'Filtro was successfully created.' }
        format.json { render :show, status: :created, location: @filtro }
      else
        format.html { render :new }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filtros/1
  # PATCH/PUT /filtros/1.json
  def update
    respond_to do |format|
      if @filtro.update(filtro_params)
        format.html { redirect_to @filtro, notice: 'Filtro was successfully updated.' }
        format.json { render :show, status: :ok, location: @filtro }
      else
        format.html { render :edit }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filtros/1
  # DELETE /filtros/1.json
  def destroy
    @filtro.destroy
    respond_to do |format|
      format.html { redirect_to filtros_url, notice: 'Filtro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filtro
      @filtro = Filtro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filtro_params
      params.require(:filtro).permit(:tipo, :termino)
    end
end

app/controllers/reclamos_controller.rb
class ReclamosController < ApplicationController
  before_action :set_reclamo, only: [:show, :edit, :update, :destroy]

  def index
    @reclamos = Reclamo.all
    respond_with(@reclamos)
  end

  def show
    respond_with(@reclamo)
  end

  def new
    @reclamo = Reclamo.new
    respond_with(@reclamo)
  end

  def edit
  end

  def create
    @reclamo = Reclamo.new(reclamo_params)
    @reclamo.save
    respond_with(@reclamo)
  end

  def update
    @reclamo.update(reclamo_params)
    respond_with(@reclamo)
  end

  def destroy
    @reclamo.destroy
    respond_with(@reclamo)
  end

  private
    def set_reclamo
      @reclamo = Reclamo.find(params[:id])
    end

    def reclamo_params
      params.require(:reclamo).permit(:tweet, :compania, :tipo, :servicio)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:contenido, :fecha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compania_helper.rb
module CompaniaHelper
end

app/helpers/diccionarios_helper.rb
module DiccionariosHelper
end

app/helpers/filtros_helper.rb
module FiltrosHelper
end

app/helpers/localizacions_helper.rb
module LocalizacionsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/reclamos_helper.rb
module ReclamosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/reclamos/_form.html.erb
<%= form_for(@reclamo) do |f| %>
  <% if @reclamo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reclamo.errors.count, "error") %> prohibited this reclamo from being saved:</h2>

      <ul>
      <% @reclamo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet %><br>
    <%= f.text_field :tweet %>
  </div>
  <div class="field">
    <%= f.label :compania %><br>
    <%= f.text_field :compania %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :servicio %><br>
    <%= f.text_field :servicio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reclamos/edit.html.erb
<h1>Editing reclamo</h1>

<%= render 'form' %>

<%= link_to 'Show', @reclamo %> |
<%= link_to 'Back', reclamos_path %>

app/views/reclamos/index.html.erb
<h1>Listing reclamos</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>Compania</th>
      <th>Tipo</th>
      <th>Servicio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reclamos.each do |reclamo| %>
      <tr>
        <td><%= reclamo.tweet %></td>
        <td><%= reclamo.compania %></td>
        <td><%= reclamo.tipo %></td>
        <td><%= reclamo.servicio %></td>
        <td><%= link_to 'Show', reclamo %></td>
        <td><%= link_to 'Edit', edit_reclamo_path(reclamo) %></td>
        <td><%= link_to 'Destroy', reclamo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reclamo', new_reclamo_path %>

app/views/reclamos/new.html.erb
<h1>New reclamo</h1>

<%= render 'form' %>

<%= link_to 'Back', reclamos_path %>

app/views/reclamos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @reclamo.tweet %>
</p>

<p>
  <strong>Compania:</strong>
  <%= @reclamo.compania %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @reclamo.tipo %>
</p>

<p>
  <strong>Servicio:</strong>
  <%= @reclamo.servicio %>
</p>

<%= link_to 'Edit', edit_reclamo_path(@reclamo) %> |
<%= link_to 'Back', reclamos_path %>